---
title: "Projet IF36"
author: "Baptiste Toussaint"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
urlcolor: blue
---

<!-- Zones de paramètres pour le rapport final -->

```{r setup, include=FALSE}
# Option d'affichage utile pour les chunk de code
knitr::opts_chunk$set(
    echo = TRUE, # Affiche les blocs de code
    cache = TRUE # Permet de mettre les données de compilation en cache pour 
    # Accélérer la compilation
)
rm(list=ls())
```

<!-- Début du rapport -->

# Analyse : GitHub Public Repository Metadata

> Projet de *Data visualization* de l'unité d'enseignement IF36 de l'[Université de Technologie de Troyes (UTT)](https://www.utt.fr/).

Nom du groupe : ***La cité de la*** <blue>f</blue> ***eur***.

Membres : [Baptiste Toussaint](https://github.com/I3at57), [XU Shilun](https://github.com/yvlann), [Louis Duhal Berruer](https://github.com/louisduhalberruer)

Langue : Français

------------------------------------------------------------------------

```{r child="./src/parts/0-introduction.Rmd"}
```

```{r child="./src/parts/1-mesureDeLaPopularite.Rmd"}
```

```{r child="./src/parts/2-etudeDesLangues.Rmd"}
```

```{r child="./src/parts/3-etudeDesContributeurs.Rmd"}
```

```{r child="./src/parts/annexes.Rmd"}
```